/// Flutter icons TimerIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TimerIcons
///      fonts:
///       - asset: fonts/TimerIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class TimerIcons {
  TimerIcons._();

  static const _kFontFam = 'TimerIcons';
  static const String? _kFontPkg = null;

  static const IconData add_to_favorites = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite__1_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
